name: hwgui linux

on:
  push:
#  schedule:
#   - cron: "30 4 1 * *"
  workflow_dispatch:
    inputs:
      name:
        description: 'hwgui linux'
        default: 'hwgui_linux'
        required: true

jobs:

  Build:
    runs-on: ubuntu-18.04
    steps:

    - name: Build
      run: |
         cd /tmp
         sudo apt-get install libgtk2.0-dev
         ls -la /usr/include
         find /usr/include -name 'gtk.h'
         find /usr/include -name 'cairo.h'
         find /usr/include -name 'gio.h'
         find /usr/include -name 'pango.h'
         find /usr -name 'glibconfig.h'
         find /usr -name 'gtkconfig.h'
         git clone https://github.com/JoseQuintas/harbour_34 /tmp/harbour --depth 1
         git clone https://github.com/JoseQuintas/hwgui /tmp/harbour/addons/hwgui --depth 1
         cd /tmp/harbour
         sudo make install
         cd /tmp/harbour/addons/hwgui
         hbmk2 -rebuild hwgui.hbp
         hbmk2 -rebuild hbxml.hbp
         hbmk2 -rebuild hwgdebug.hbp
         hbmk2 -rebuild procmisc.hbp
#         build-essential gnome-themes-standard libglib2.0-dev g-nome-themes-standard libcairo2-dev
